---
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 11
extends:
  - airbnb-base
rules:
  no-console: off
  import/extensions: off
  no-await-in-loop: off
