# .eslintrc.yml
env:
  browser: true
  es2020: true
extends:
  - airbnb-base
parserOptions:
  sourceType: module
  ecmaVersion: 11
rules:
  no-console: off
  import/extensions: off
  no-await-in-loop: off
